[package]
name = "dcsctp-cxx"
version = "0.1.0"
publish = false
description = "C++ FFI for dcsctp"
edition = "2021"

[dependencies]
dcsctp = { path = ".." }
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"

[lib]
crate-type = ["staticlib"]
