name: Continuous Integration

on:
  push:
  pull_request:

permissions: read-all

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose

  fuzz:
    name: fuzz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
        with:
          toolchain: nightly
      - name: Sanity check fuzzers
        run: |
          cargo install cargo-fuzz
          cd fuzz
          cargo fuzz run parse_parameters -- -max_total_time=5
          cargo fuzz run parse_error_causes -- -max_total_time=5
          cargo fuzz run parse_packet -- -max_total_time=5

  check-rustfmt:
    name: check (rustfmt)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
        with:
          toolchain: nightly
          components: rustfmt
      - run: cargo fmt --all -- --check

  check-clippy:
    name: check (clippy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
        with:
          components: clippy
      - run: cargo clippy --all-features --all-targets -- -D warnings

  check-doctests:
    name: check (doctests)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
      # NOTE: We need to run `cargo test --doc` separately from normal tests:
      # https://github.com/rust-lang/cargo/issues/6669
      - name: Run doctests
        run: cargo test --doc
        env:
          RUST_BACKTRACE: 1
      - name: Check `cargo doc` for lint issues
        env:
          RUSTDOCFLAGS: "--deny warnings"
        run: cargo doc --no-deps --all-features --document-private-items

  build-cxx:
    name: cxx (build)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
      - name: Build and sanity test
        run: |
          cd cxx/examples/pingpong/
          make clean all
          ./main
