name: Continuous Integration

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  STABLE_TOOLCHAIN: 1.92.0
  NIGHTLY_TOOLCHAIN: nightly-2025-12-16

jobs:
  build_and_test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.STABLE_TOOLCHAIN }}
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose

  fuzz:
    name: fuzz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.NIGHTLY_TOOLCHAIN }}
      - name: Sanity check fuzzers
        run: |
          cargo install cargo-fuzz
          cd fuzz
          cargo fuzz run parse_parameters -- -max_total_time=5
          cargo fuzz run parse_error_causes -- -max_total_time=5
          cargo fuzz run parse_packet -- -max_total_time=5

  check-rustfmt:
    name: check (rustfmt)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.NIGHTLY_TOOLCHAIN }}
          components: rustfmt
      - run: cargo fmt --all -- --check

  check-clippy:
    name: check (clippy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.STABLE_TOOLCHAIN }}
          components: clippy
      - run: cargo clippy --all-features --all-targets -- -D warnings

  check-doctests:
    name: check (doctests)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.STABLE_TOOLCHAIN }}
      # NOTE: We need to run `cargo test --doc` separately from normal tests:
      # https://github.com/rust-lang/cargo/issues/6669
      - name: Run doctests
        run: cargo test --doc
        env:
          RUST_BACKTRACE: 1
      - name: Check `cargo doc` for lint issues
        env:
          RUSTDOCFLAGS: "--deny warnings"
        run: cargo doc --no-deps --all-features --document-private-items

  build-cxx:
    name: cxx (build)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.STABLE_TOOLCHAIN }}
      - name: Build and sanity test
        run: |
          cd dcsctp-cxx/
          make clean all run
